# This is a basic workflow to help you get started with Actions

name: duvan salazar pulido

# Controls when the workflow will run
on:mas ordenes 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ] clientes 1,2,3,4
  pull_request:
    branches: [ "main" ] zona ampliada 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: radar batchs 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:ordenes 
  # This workflow contains a single job called "build"
  build: mejor pagadas 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
